### ISSUE TITLE
Consider removing logic to download kernel headers for CentOS

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#1019]
In https://github.com/kinvolk/inspektor-gadget/pull/76/commits/30f49a66b243378afa1b4090e7f3c61601541a2f we added logic to download and install the kernel headers for CentOS when they were not available on the host. Inspektor Gadget and the ecosystem has changed a lot since that, all of our gadgets use BTF and it's available on a lot of distros now, even in CentOS. I think it's time for us to remove that logic to simplify this entrypoint script and avoid us having to handle things like https://github.com/kinvolk/inspektor-gadget/pull/1012#issuecomment-1268506295. 

@alban do you have any opinions on this? (since you added that initial support)

**Comment by alban** [comment]
I agree
