### ISSUE TITLE
support aws eks 1.16

### ISSUE THREAD

**Issue by aavileli** [kinvolk/inspektor-gadget#112]
does not work on aws eks 1.16 
```
NODE Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module)
[E2] chdir(/lib/modules/4.14.177-139.253.amzn2.x86_64/build): No such file or directory
[E2] Traceback (most recent call last):```

**Comment by alban** [comment]
Thanks for the report.

I suspect it will be fixed with https://github.com/kinvolk/inspektor-gadget/pull/110 but I have not tested yet.

Is the package `kernel-devel` installed on the host?

Is the `build` directory a symbolic link, and what does it point to?
```
ls -l /lib/modules/4.14.177-139.253.amzn2.x86_64/build
```

**Comment by aavileli** [comment]
Yep the kernel-headers are installed.
The directory is a symlink to usr/src/kernels/4.14.177-139.253.amzn2.x86_64.

**Comment by alban** [comment]
Hi @aavileli, #110 is merged now. Do you have some time to try it on your eks setup?

**Comment by aavileli** [comment]
Hi @alban 

I compiled the latest master it works now.

Thanks
