### ISSUE TITLE
Check minikube support with pod informer

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#115]
BCC-based gadgets should work now with in minikube with the pod informer introduced in https://github.com/kinvolk/inspektor-gadget/pull/113.

I have some some quick experiments following https://minikube.sigs.k8s.io/docs/tutorials/ebpf_tools_in_minikube/ but I wasn't able to get this working because a weird error while extracting the headers:

```
....
./net/bridge/br_netfilter.mod.o
./net/bridge/br_sysfs_br.c
./net/bridge/br_stp_if.c
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

The scope of this issue is to update the contributing guide to include information about how to test BCC-based gadgets once it's working.

**Comment by alban** [comment]
It works for me with the following changes:
- https://github.com/kubernetes/minikube/pull/8582 (CONFIG_IKHEADERS)
- https://github.com/kubernetes/minikube/pull/8607 (documentation update)

**Comment by mauriciovasquezbernal** [comment]
It works fine also when using `--driver=docker`. Closing this issue as the error I was hitting was a problem on my local machine only.
