### ISSUE TITLE
gadget pod fails to start in OpenShift's playground due to missing kernel headers

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/inspektor-gadget#120]
I was trying to follow the [OpenShift tutorial](https://docs.google.com/document/d/1ko2ft4eDLJK7uigLHu88AOHZ-bhrNfV84lQvoczfcYI/edit) for inspektor gadget and couldn't do much because the gadget pod fails to start.

The last lines in the pod log are:
```
Fetching kernel-devel from CentOS 8
curl: (22) The requested URL returned error: 404 Not Found
```

This happens because IG tries to download the kernel headers for the running kernel. In this case, the playground has version `4.18.0-147.0.3.el8_1.x86_64`. But that version is not available in the CentOS URL that IG queries (http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/)

This is the line that causes the failure:
https://github.com/kinvolk/inspektor-gadget/blob/master/gadget-container/entrypoint.sh#L68

Downloading the source wouldn't be needed if the kernel had `CONFIG_IKHEADERS`, but I guess they'd need to upgrade to 5.4 before that.

**Comment by blanquicet** [comment]
Fixed by https://github.com/kinvolk/inspektor-gadget/pull/486
