### ISSUE TITLE
Cannot install gadget on mac

### ISSUE THREAD

**Issue by wardhane** [kinvolk/inspektor-gadget#121]
I tried to install gadget using krew and got the below error. 

`k krew install gadget
Updated the local copy of plugin index.
F0730 11:48:45.907236   58411 root.go:52] failed to load plugin "gadget" from the index: platform ({Head: URI:https://github.com/kinvolk/inspektor-gadget/releases/download/v0.2.0/inspektor-gadget-linux-amd64.tar.gz Sha256:b2d5e70a5caa4adfa3918e8a70702cd4a118d5ebafc091d5b4d7ec4ea0caf390 Selector:&LabelSelector{MatchLabels:map[string]string{arch: amd64,os: linux,},MatchExpressions:[],} Files:[] Bin:kubectl-gadget}) is badly constructed: can't have a plugin without specifying file operations`

My krew version is

`╰ k krew version
OPTION          VALUE
IsPlugin        true
ExecutedVersion dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a
GitTag          v0.2.1
GitCommit       cd2c6e1
IndexURI        https://github.com/GoogleContainerTools/krew-index.git
BasePath        /Users/harsha/.krew
IndexPath       /Users/harsha/.krew/index
InstallPath     /Users/harsha/.krew/store
DownloadPath    /var/folders/bq/1tcndjlx4516`

Thanks

**Comment by mauriciovasquezbernal** [comment]
Hi @wardhane, 

Could you update krew to `0.3.X`?, `0.2.X` performs the template validation in a different way and our current template is not compatible with it.

Thanks.

**Comment by mauriciovasquezbernal** [comment]
@wardhane did you have the change to try it out? Thanks!

**Comment by mauriciovasquezbernal** [comment]
Closing this issue. Please re-open if it's still relevant.

**Comment by wardhane** [comment]
Mauricio,

Apologies for not replying earlier. I will verify and get back to you
tomorrow.

Thanks
Harsha
