### ISSUE TITLE
gadget-container: Liveness probes are missing

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#127]
The gadget Pod doesn't include any liveness probe, if there is any crash it'll be unnotice and the Pod will became unusable.

https://github.com/kinvolk/inspektor-gadget/blob/669dcdb204b12b19a0a67b6447cc4c03ea40357f/gadget-container/entrypoint.sh#L136

A liveness probe checking that the gadget tracer manager is accepting grpc requests inside the pod should be added. Kubernetes doesn't support grpc probes, probably https://github.com/grpc-ecosystem/grpc-health-probe is a good tool to use: https://medium.com/@github.gkarthiks/implementing-healthchecks-in-grpc-containers-for-kubernetes-d5049989ab12.

**Comment by alban** [comment]
The gadgettracermanager binary is both the grpc client and server. It could be used as a client in the liveness probe.
