### ISSUE TITLE
Improve GKE support by automatically downloading headers

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/inspektor-gadget#131]
It's currently possible to use inspektor-gadget in GKE (which runs a Flatcar relative, called COS - Container Optimized OS), as long as headers are available. But injecting the kernel headers requires quite some tweaking.  We could automate this in a similar way to how getting headers for Red Hat was automated. This is what I discovered from my test.

Documentation for where to get the headers is here: https://cloud.google.com/container-optimized-os/docs/resources/sources

`/etc/os-release` in the GKE node I tested on had:
```
BUILD_ID=12371.251.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=5d4ffd91281840f7a118143d77fbefb02e87943c
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=77
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=77
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos
```

The BUILD_ID can be used to get the headers from the GCS bucket mentioned above. Like this:
`https://storage.googleapis.com/cos-tools/${BUILD_ID}/kernel-headers.tgz`

This tarball contains a `./usr/src/linux-headers-$(uname -r)/` folder.

Interestingly the symlink in `/lib/modules/$(uname -r)/source` doesn't just point to the uname, but it references this "lakitu" string that appears in several things related to COS:

```
$ readlink /lib/modules/$(uname -r)/source
../../../usr/src/lakitu-kernel-4_19-4.19.112
```

So, the command to create the right link would be (in the decompressed `/usr/src`):
`ln -s linux-headers-$(uname -r) $(basename $(readlink /lib/modules/$(uname -r)/source))`

And then this folder should be binmounted into the /usr/src folder:
`sudo mount -o bind /tmp/usr/src /usr/src`

So, something like this might work (I haven't tested it, just basing it on the RPM example, this needs testing and probably has bugs):

```
if grep -q '^ID="cos"$' /host/etc/os-release > /dev/null ; then
  if [ ! -d "/host/usr/src/kernels/$(uname -r)" ] ; then
    echo "Fetching kernel-headers from cos-tools."
    BUILD_ID=$(sed -n '/^BUILD_ID=/ s/^BUILD_ID=//p' /host/etc/os-release)
    BUCKET=https://storage.googleapis.com/cos-tools/${BUILD_ID}
    HEADER_FILE=kernel-headers.tgz
    KERNELDIR=/var/lib/gadget-kernel/
    HOSTKERNELDIR=/host${KERNELDIR}
    mkdir -p $HOSTKERNELDIR/
    test -r $HOSTKERNELDIR/$HEADER_FILE || \
        curl -fsSLo $HOSTKERNELDIR/$HEADER_FILE $BUCKET/$HEADER_FILE
    HEADERDIR="linux-headers-$(uname -r)"
    test -r $HOSTKERNELDIR/usr/src/${HEADERDIR} || \
        tar -C $HOSTKERNELDIR -xzf $HEADER_FILE
    EXPECTEDDIR=$(basename $(readlink /lib/modules/$(uname -r)/source))
    test -r $HOSTKERNELDIR/usr/src/${EXPECTEDDIR} || \
        ln -s ${HEADERDIR} $HOSTKERNELDIR/usr/src/${EXPECTEDDIR}
    mount --bind $HOSTKERNELDIR/usr/src /usr/src
  fi
fi
```

**Comment by bdegeeter** [comment]
Does anyone know if this is still an issue?  I'm focusing on using traceloop in GKE and can spend some time working on an update.

**Comment by pothos** [comment]
Traceloop and the BCC tools are different, you can give it a try to validate that it works:
```
sudo docker run --rm -v /sys/kernel/debug:/sys/kernel/debug -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/fs/bpf:/sys/fs/bpf -v /run:/run --privileged docker.io/kinvolk/traceloop traceloop cgroups "$(find /sys/fs/cgroup/ -name systemd-journald.service | head -n 1)"
# or use the /sys/fs/cgroup/ path to any other cgroups you want to trace, systemd-journald is just an example
```

**Comment by marga-kinvolk** [comment]
We are moving away from kernel headers and instead focusing on BTF support, which can be directly enabled by the kernel, or added on top by using BTFGen. Thus, I'm closing this bug as we won't be working on this.
