### ISSUE TITLE
Create container image for building the demo gifs 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#134]
Updating the demo gifs is a bit complicated as we use https://github.com/kinvolk/gifterminal/tree/kai/fonts-and-paths and it's not clear what are the dependencies needed to use it. It'll be nice to have a container image with everything is needed inside.

**Comment by marga-kinvolk** [comment]
We agreed that we're dropping the demo gifs, as they are too complex to keep up-to-date. While they are quite cool, keeping them updated is a burden to the team :(.
