### ISSUE TITLE
invalid guessing state while guessing uts namespace, got checking expected checked

### ISSUE THREAD

**Issue by mattrjacobs** [kinvolk/inspektor-gadget#137]
I'm evaluating this project by running it on a local Minikube installation.  When I deploy via `krew`, here is what gets logged in the `gadget` container: 
```
05:50 $ kubectl logs -n kube-system gadget-6sl8p
OS detected: "Ubuntu 20.04 LTS"
Kernel detected: 5.4.0-7642-generic
bcc detected: 0.1.8-2644.git.5fed2a94
Gadget image: docker.io/kinvolk/gadget:202007010134320f732c
Deployment options:
INSPEKTOR_GADGET_OPTION_RUNC_HOOKS_MODE=auto
INSPEKTOR_GADGET_OPTION_TRACELOOP=true
INSPEKTOR_GADGET_OPTION_TRACELOOP_LOGLEVEL=info,json
Inspektor Gadget version: v0.2.0
Falling back to podinformer runc-hook-mode.
Starting the Gadget Tracer Manager in the background...
traceloop version 3a57301
time="2020-09-21T12:50:09Z" level=info msg="Starting Pod controller"
{"level":"info","msg":"Starting pod informer","time":"2020-09-21T12:50:09Z"}
I0921 12:50:09.963990   10113 podinformer.go:268] Starting Pod controller
invalid guessing state while guessing uts namespace, got checking expected checked
```

I will poke around the source to see if I can resolve it, but it's not clear what my next step should be from the logs.

**Comment by alban** [comment]
Hi @mattrjacobs, what is your Minikube version, and which Minikube driver are you using?

Unfortunately, Inspektor Gadget requires a couple of changes in Minikube, and that work is not yet completed in Minikube upstream (https://github.com/kubernetes/minikube/issues/8556 and https://github.com/kubernetes/minikube/issues/8637). Meanwhile, you could try a Minikube build with our Minikube branch, where Inspektor Gadget should work fine:
https://github.com/kinvolk/cloud-native-bpf-workshop/blob/master/minikube.md#our-branch

**Comment by mattrjacobs** [comment]
Ah thanks - those pointers are great.

I am currently running Minikube 1.13 with the Docker driver:
```
06:39 $ minikube start
😄  minikube v1.13.0 on Debian bullseye/sid
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.19.0 on Docker 19.03.8 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube" by default
```

**Comment by TheKangaroo** [comment]
I got the same error on MacOS inside a kind Cluster
```
MacOS: 11.2.3
kind version: 0.10.0
k8s version: v1.20.2
```
Would be great to test this on a local installation.

**Comment by marga-kinvolk** [comment]
As mentioned by Alban, this was a known issue regarding the eBPF compatibility in minikube. We provide a minikube image in the https://github.com/kinvolk/cloud-native-bpf-workshop, that can be used with Inspektor Gadget for testing purposes (the workshop itself is outdated and would need to be updated to the latest IG version, but the Minikube image is still working and usable for testing IG functionality).

Closing as this is not actionable. Thanks for the report!
