### ISSUE TITLE
Consider switching to quay.io for the gadget image

### ISSUE THREAD

**Issue by iaguis** [kinvolk/inspektor-gadget#141]
At kinvolk we are using quay.io for pretty much all our container images.

**Comment by blanquicet** [comment]
We started the process of moving to Azure Container Registry, see https://github.com/kinvolk/inspektor-gadget/pull/566.

**Comment by marga-kinvolk** [comment]
And then we re-decided, to move to GitHub's instead of Azure: #597 

In any case, we are not moving to quay, so closing this one.
