### ISSUE TITLE
Add support for OpenShift

### ISSUE THREAD

**Issue by e-minguez** [kinvolk/inspektor-gadget#145]
**Current situation**
Currently it doesn't work because it doesn't identify the operating system and fails to install the debug packages.

**Impact**
inspektor-gadget doesn't work in OpenShift

**Ideal future situation**
Ideally, inspektor-gadget can be installed in OpenShift in a custom namespace (kube-system by default) so OpenShift users can benefit of using it as well.

**Implementation options**
There is a WIP fork https://github.com/clustership/inspektor-gadget/tree/master/openshift

**Additional information**

**Comment by mauriciovasquezbernal** [comment]
Probably related (even duplicated) https://github.com/kinvolk/inspektor-gadget/issues/120.
