### ISSUE TITLE
Windows version is still missing ?

### ISSUE THREAD

**Issue by djkormo** [kinvolk/inspektor-gadget#154]
I have still the same

kubectl krew install gadget
Updated the local copy of plugin index.
Installing plugin: gadget
W1228 21:43:26.618577    3600 install.go:164] failed to install plugin "gadget": plugin "gadget" does not offer installation for this platform
F1228 21:43:26.636580    3600 root.go:79] failed to install some plugins: [gadget]: plugin "gadget" does not offer installation for this platform
exit status 255

_Originally posted by @djkormo in https://github.com/kinvolk/inspektor-gadget/issues/135#issuecomment-751858366_

**Comment by mauriciovasquezbernal** [comment]
@djkormo ops, I'm so sorry for closing the other issue, I lost the context and closed it thinking it was solved. 

Now it should work, I added Windows support in the krew template (https://github.com/kubernetes-sigs/krew-index/pull/970), I did some testing in a Windows machine and it appears to be working good. 

It would be great if you can confirm if it works and we can close this issue. Thanks!

**Comment by mauriciovasquezbernal** [comment]
https://github.com/kubernetes-sigs/krew-index/pull/970#issuecomment-755945197 indicates it worked, closing this issue.
