### ISSUE TITLE
Error while running network-policy

### ISSUE THREAD

**Issue by gkumarchilakala** [kinvolk/inspektor-gadget#155]
Im getting below error while running the network-policy on a RKE based kubernetes cluster. What is the fix for this error?

$ kubectl gadget network-policy monitor --namespace default --output network.log
failed to init perf map for IPv4 events: error guessing offsets: invalid guessing state while guessing destination address IPv6, got checking expected checked
Error detected: "Error running command: \"command terminated with exit code 1\"\n"

**Comment by alban** [comment]
Thanks for reporting this.

I can reproduce the bug with the following steps:

```
$ docker-machine create -d virtualbox \
  --virtualbox-boot2docker-url https://releases.rancher.com/os/latest/rancheros.iso \
  --virtualbox-memory 2048 \
  rancheros
$ docker-machine ssh rancheros
```
Then:
```
$ uname -a
Linux rancheros 4.14.138-rancher #1 SMP Sat Aug 10 11:25:46 UTC 2019 x86_64 GNU/Linux

$ docker run -ti --rm --privileged -v /sys/kernel/debug:/sys/kernel/debug -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/fs/bpf:/sys/fs/bpf -v /run:/run --entrypoint=/bin/bash docker.io/kinvolk/gadget

# networkpolicyadvisor -kubeconfig ./kubeconfig
failed to init perf map for IPv4 events: error guessing offsets: invalid guessing state while guessing source address, got checking expected checked
```

I'll try to debug this.

**Comment by alban** [comment]
Actually I cannot reproduce the issue when I add `--net=host --pid=host`, which should be set in the gadget DaemonSet.

Which kernel do you have?

**Comment by marga-kinvolk** [comment]
This bug has had months of inactivity, so I'm going to close it now. If you experience this or a similar issue, please file a new report providing as much information as possible.
