### ISSUE TITLE
Gadget container failure at startup (traceloop / Go runtime)

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#186]
## Description

During startup, sometimes the gadget container fails with the following error:
```
OS detected: "Linux Mint 20.1"
Kernel detected: 5.4.0-58-generic
bcc detected: 0.1.8-2644.git.5fed2a94
Gadget image: docker.io/blanquicet/gadget:issue-liveness
Deployment options:
INSPEKTOR_GADGET_OPTION_HOOK_MODE=auto
INSPEKTOR_GADGET_OPTION_TRACELOOP=true
INSPEKTOR_GADGET_OPTION_TRACELOOP_LOGLEVEL=info,json
Inspektor Gadget version: v0.2.1-27-ga0058af-dirty
Falling back to podinformer hook.
Starting the Gadget Tracer Manager in the background...
traceloop version 6f4efc6
{"level":"info","msg":"Starting pod informer","time":"2021-06-28T17:00:17+02:00"}
I0628 17:00:17.823683  399212 podinformer.go:282] Starting Pod controller
time="2021-06-28T17:00:17+02:00" level=info msg="Starting Pod controller"
error while loading "tracepoint/raw_syscalls/sys_exit" (resource temporarily unavailable):
processed 1 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
```

## Impact

Such failure cause container to be restarted.

## Environment and steps to reproduce

This issue was reproduced while testing liveness probe feature #127 and container is restarted frequently. During such tests, kubeadm was used to create the cluster on a Linux Mint 20.1 with kernel 5.4.0-58-generic.

The issues was not reproduced if traceloop is disabled.

## Additional information

Preliminary analysis found that error `error while loading "tracepoint/raw_syscalls/sys_exit" (resource temporarily unavailable)`, seems to happen during the verifying process in the bpf() system call. 

It could be related to new strategy introduced in new versions of Go runtime (Probably from 1.14) when SIGURG is sent between Go runtime threads.

Following some useful links:
- https://github.com/iovisor/gobpf/blob/master/elf/elf.go#L630-L635
- https://github.com/iovisor/gobpf/blob/master/elf/elf.go#L208
- https://github.com/torvalds/linux/blob/master/kernel/bpf/verifier.c#L10643-L10644

**Comment by marga-kinvolk** [comment]
I believe we are not seeing this anymore, due to the fact that we've disabled traceloop on startup, is that correct? Can we close this bug in that case?

**Comment by mauriciovasquezbernal** [comment]
Traceloop is disabled by default and we're planning to rework it on https://github.com/kinvolk/inspektor-gadget/issues/371, so I think we can close this issue now.
