### ISSUE TITLE
[RFE] Trace Controller: documentation (#197 follow-up)

### ISSUE THREAD

**Issue by alban** [kinvolk/inspektor-gadget#205]
#197 added a new controller for the `Trace` custom resource but the documentation is missing:
- [ ] Document how users should use the Trace custom resource. There could be several categories of users:
  - Users accessing custom resources directly with kubectl
  - The kubectl-gadget CLI
  - Graphical interfaces such as Headlamp plugins
  - Other software consuming low-level insights from Inspektor Gadget
- [ ] Document how developers can implement new gadgets that are controlled by the Trace resource

**Comment by mauriciovasquezbernal** [comment]
Should we put it on the v0.5.0 milestone?

**Comment by marga-kinvolk** [comment]
I believe this was fixed with #363
