### ISSUE TITLE
Cannot install plugin on Apple Silicon (darwin/ARM64)

### ISSUE THREAD

**Issue by sammcj** [kinvolk/inspektor-gadget#241]
## Description

Installing the plugin on any mac with an M1 / Apple Silicon processor errors:

```
kubectl krew install gadget
Updated the local copy of plugin index.
Updated the local copy of plugin index "kvaps".
Installing plugin: gadget
W0829 13:46:24.860152   11172 install.go:164] failed to install plugin "gadget": plugin "gadget" does not offer installation for this platform
F0829 13:46:24.860211   11172 root.go:79] failed to install some plugins: [gadget]: plugin "gadget" does not offer installation for this platform
```

## Impact

I can't use the plugin, but it's not the end of the world or impacting any systems.

## Environment and steps to reproduce

1. **Set-up**: Any Apple M1 based hardware (or cloud instance)
2. **Task**: install krew, try to install this plugin
3. **Action(s)**: as above
4. **Error**:  as above

## Expected behaviour

The plugin to install

## Additional information

I'm assuming it's probably something as simple as adding an extra build target somewhere?

**Comment by alban** [comment]
@sammcj Thanks for the report! I prepared a fix (https://github.com/kinvolk/inspektor-gadget/pull/255) but I don't have the hardware to test it. Would you be able to test it?

**Comment by sammcj** [comment]
@alban thank you! Yes I have an M1 machine I can test in on if there's a way I can install it without it being released?

**Comment by alban** [comment]
@sammcj I made a fake release on my personal fork. You could download the tarball for your machine and try it:
https://github.com/alban/inspektor-gadget/releases/tag/v0.3.0-rc3

Alternativaly, you could checkout the branch and compile it yourself (see [Building the code](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/CONTRIBUTING.md#building-the-code)), but you would need to build both `kubectl-gadget` and the container image, and push it to your own container registry to be able to test it.

**Comment by sammcj** [comment]
Sorry was AFK for a few days, thank you so much for this!
