### ISSUE TITLE
kubectl-gadget: Improve error message when the node doesn't exist

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#252]
## Description

As discussed in #238 (comment), the error messages when (1) the timeout happens before the gadget pod writes the result in Trace.Status and (2) a non-existent node is used as filter should be improved:

```
./kubectl-gadget-linux-amd64 socket-collector -n default -p my-pod --node non-existent-node
FATA[0000] Error getting traces from all nodes           args="[]" command="kubectl-gadget socket-collector"
```

## Impact

User does not know what happened. Gadget is just failing without a proper error message.

## Environment and steps to reproduce

1. **Set-up**: There is no particular requirements, it should be reproducible everywhere. In my case I was using: Kubernetes cluster created using kubeadm v1.22.0, Docker v20.10.8, Go v1.16.7 and kernel 5.13.9.
2. **Task**: Filter by a non existent node.
3. **Action(s)**: Execute the socket-collector gadget with a non-existent node in the filter: `kubectl gadget socket-collector -n default -p my-pod --node non-existent-node`
4. **Error**: The gadget just fails without giving any information to the user.

## Expected behavior

Error should describe why gadget failed.

## Additional information

This improvement complements the issue https://github.com/kinvolk/inspektor-gadget/issues/251 and they should be considered together.

**Comment by marga-kinvolk** [comment]
I'm not sure I see the difference between this issue and #251. In this one you're saying that the error message should be improved. In the other, you are saying that the case of the node not being present should be handled... Isn't handling this non-existent node the way of improving the error message? Or did you have something else in mind?

**Comment by blanquicet** [comment]
With this issue, I was trying to create a more general bug to ensure we are handling all the error cases, so far we have discovered two uncovered cases (non-existent pod and timeout) but there could be more. It means that by solving this issue we will implicitly solve #251. 

In other words, you're right, they overlap so we could just keep this one given that it is more general.

**Comment by marga-kinvolk** [comment]
Ah, I see. I'm not a fan of "general" issues, because it's hard to know when we are done improving all error messages. In that case, I think it's better to close this bug and then whenever we encounter an error message that's not helpful, make that one better.

**Comment by blanquicet** [comment]
Closing this bug as per previous discussion.
