### ISSUE TITLE
[RFE] Permit using the seccomp policy advisor without BTF

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/inspektor-gadget#264]
## Current situation

The seccomp policy advisor can only be used with kernels that have BTF enabled. Having kernel headers installed is not enough to be able to run it.

## Impact

Not many distributions have BTF enabled yet. For example, even though 5.8 and 5.11 are available for Ubuntu Focal, those don't come with BTF enabled. Ubuntu Users need to run either Groovy or Hirsute to get a kernel with BTF enabled. This means that this gadget is currently quite hard even to test.

## Ideal future situation

While using BTF and CO-RE will be great in the future, as more and more distros adopt it, in the meantime we should also allow gadgets to run with the old kernel headers setup.

**Comment by alban** [comment]
Symptoms:
```
OperationError: Failed to start seccomp tracer: failed to create BPF collection:
program tracepoint__raw_syscalls__sys_enter:
CO-RE relocations: no BTF for kernel version 5.8.0-1040-azure: not supported
```

**Comment by alban** [comment]
Note that the seccomp gadget now works on AKS despite the lack of BTF support in the kernel thanks to:
- https://github.com/aquasecurity/btfhub/pull/6
- https://github.com/kinvolk/inspektor-gadget/pull/326

**Comment by marga-kinvolk** [comment]
We discussed this in more detail yesterday. Adding support for the "old" way, i.e. using kernel headers instead of BTF is a significant amount of work, and we are not sure that there are users out there that will care about that.

Until we get user requests for this feature, our time is better spent improving the support of BTF, for example by working together with the btfhub people so that they have more kernels there, or upstreaming the work done for btfgen so that more people can use it.

**Comment by marga-kinvolk** [comment]
We now have BTFGen integrated which means that we get BTF support even for kernels that don't ship with BTF enabled. Thus, I'm closing this bug.
