### ISSUE TITLE
docs: process collector CLI documentation is missing 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#280]
There is some auto-generated documentation for the process-collector [here](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/gadgets/process-collector.md) but some examples and documentation about how to use it from the kubectl gadget CLI is missing.

**Comment by marga-kinvolk** [comment]
Moving to 0.3.1, I don't think this is a release blocker for 0.3
