### ISSUE TITLE
docs: dns gadget documentation is missing

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#282]
We have some documentation regarding the DNS gadget and its usage through the CRD [here](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/gadgets/dns.md) but we're missing how to use it from the CLI.

**Comment by marga-kinvolk** [comment]
Moving to 0.3.1, I don't think this is a release blocker for 0.3
