### ISSUE TITLE
Distribute via krew (kubectl plugin manager)

### ISSUE THREAD

**Issue by alban** [kinvolk/inspektor-gadget#30]
[krew](https://github.com/kubernetes-sigs/krew) is a plugin manager for kubectl. Plenty of kubectl plugins have an installation method with krew ([see the list](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md)). Inspektor Gadget could join that list.

```
$ kubectl krew install gadget
```

/cc @ahmetb @invidian

**Comment by aristosvo** [comment]
This is my initial writeup of the yaml necessary for Krew. As I'm currently running on OSX, I'm waiting for the first release containing OSX to evaluate this as well. 

The choice for `network-policy` as the example is a bit arbitrary, but as it's my primary reason to look at Inspektor gadget it made sense to me. Feel free to correct me if I'm wrong.
```
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: gadget
spec:
  version: "v0.1.0-alpha.5"
  platforms:
  - uri: https://github.com/kinvolk/inspektor-gadget/releases/download/v0.1.0-alpha.5/inspektor-gadget.tar.gz
    sha256: 327abda851fcbd8cd7a4a69c0c50c5f2d93b1abed00c901eb78a083fd0d2cbfb
    bin: kubectl-doctor
    files:
    - from: "inspektor-gadget"
      to: "."
    selector:
      matchLabels:
        os: linux
        arch: amd64
  shortDescription: Collection of gadgets for Kubernetes developers
  homepage: https://github.com/kinvolk/inspektor-gadget
  description: |
    Inspektor Gadget is a collection of tools (or gadgets) for developers
    of Kubernetes applications. While it is primarily designed for 
    Lokomotive, Kinvolk's open-source Kubernetes distribution, it can be 
    used on other Kubernetes distributions.Inspektor Gadget is deployed 
    to each node as a privileged DaemonSet.It uses in-kernel BPF helper 
    programs to monitor events mainly related to syscalls from userspace 
    programs in a pod. The BPF programs are run by the kernel and gather
    the log data. Inspektor Gadget's userspace utilities fetch the log 
    data from ring buffers and display it.

    What BPF programs are and how Inspektor Gadget uses them is briefly 
    explained here:
    https://github.com/kinvolk/inspektor-gadget/blob/master/Documentation/architecture.md
    
  caveats: |
    Usage:
        Inspektor Gadget is a collection of tools (or gadgets) for developers
        Install Inspektor Gadget on Kubernetes:
        $ kubectl gadget deploy | kubectl apply -f -

        One of the gadgets is the network-policy gadget
        The network-policy gadget monitors the network activity and record 
        the list of new TCP connections in a file. This file can then be used
        to generate Kubernetes network policies.

          In one terminal, start the network-policy gadget recording:
          $ kubectl gadget network-policy monitor --namespaces demo \
            --output ./networktrace.log

          At some point, let's stop the recording with Ctrl-C, and generate 
          the Kubernetes network policies:
          $ kubectl gadget network-policy report \
            --input ./networktrace.log > network-policy.yaml
```

**Comment by mauriciovasquezbernal** [comment]
Hi @aristosvo, thanks so much for working on it.

Unfortunately I failed to assign this issue to me some days ago and we ending up doing duplicated work. I had started to draft a manifest [here](https://github.com/kinvolk/krew-index/commit/42551755cfa88739c5d5a5d45a43a221a36e4777) and to update the release process to make it more krew friendly [here](https://github.com/kinvolk/inspektor-gadget/tree/mauricio/prepare-for-krew).

We are planning to do a new release soon (after https://github.com/kinvolk/inspektor-gadget/pull/58 is merged), after that we'll open a PR against krew-index. Once it's done, would you mind taking a look and testing it (specially in OSX as I don't have access to this system)?

Thanks a lot.

**Comment by aristosvo** [comment]
@mauriciovasquezbernal No problem, I'm more interested in the functionality than anything else, thanks for pushing it!

I'll take a look ASAP, do you have a draft PR somewhere?

**Comment by mauriciovasquezbernal** [comment]
hi @aristosvo, we opened a PR for it https://github.com/kubernetes-sigs/krew-index/pull/628, we did a small check and it works on OSX too. It'll be great if you can confirm.

**Comment by mauriciovasquezbernal** [comment]
Solved by https://github.com/kinvolk/inspektor-gadget/pull/95.
