### ISSUE TITLE
[RFE] Add CLI for the biolatency 

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#309]
## Current situation

Using the biolatency gadget currently requires creating and annotating a CR.

## Impact

The UX is not that good.

## Ideal future situation

Add command `kubectl gadget biolatency`.

## Additional information

- Check issue https://github.com/kinvolk/inspektor-gadget/issues/263 to align the usage with the network and seccomp policy advisors.

Additional tasks (#394):
- [ ] Do not forget to also create the CLI documentation in docs/guides
- [ ] Update the [kernel requirements](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/install.md#required-kernel-versions) documentation

**Comment by mauriciovasquezbernal** [comment]
I'm wondering if we should reuse the CR for the gadget our call it directly like biotop in https://github.com/kinvolk/inspektor-gadget/pull/303.

**Comment by mauriciovasquezbernal** [comment]
Fixed by https://github.com/kinvolk/inspektor-gadget/pull/389.

**Comment by mauriciovasquezbernal** [comment]
Well no actually, documents are missing :D
