### ISSUE TITLE
Improve CI/CD for external contributors

### ISSUE THREAD

**Issue by alban** [kinvolk/inspektor-gadget#31]
Inspektor Gadget uses a GitHub action ([inspektor-gadget.yml](https://github.com/kinvolk/inspektor-gadget/blob/master/.github/workflows/inspektor-gadget.yml)) to automatically be compiled at each git-push and to produce the following artifacts:
- a [container image](https://hub.docker.com/repository/docker/kinvolk/gadget/general) with an unique tag
- inspektor-gadget.zip as a github artifact containing the kubectl plugin (and `kubectl gadget deploy` will reference the container image with the unique tag generated before)

It works fine when the branch is pushed on the main repository (https://github.com/kinvolk/inspektor-gadget) but cannot work for forks because forks don't have access to the GitHub secrets `DOCKER_USERNAME` and `DOCKER_PASSWORD` to push the container image `docker.io/kinvolk/gadget`.

We should improve this to make it easier for external contributors. Suggestions:
- Add a GitHub secrets for the container image instead of hard coding `docker.io/kinvolk/gadget`
- Update inspektor-gadget.yml to use that
- Document how external contributors can use this in a fork.

**Comment by mauriciovasquezbernal** [comment]
Solved by https://github.com/kinvolk/inspektor-gadget/pull/111.
