### ISSUE TITLE
postProcess output does not skip the first line correctly

### ISSUE THREAD

**Issue by alban** [kinvolk/inspektor-gadget#33]
In commit 6a0116f077d37f2bf90d1962b251f8dcefd2248b ("Workaround for the output disappearing"), I wrote a temporary workaround for the bug with output disappearing. However, the code is not correct:

https://github.com/kinvolk/inspektor-gadget/blob/bce84c31b5c535c340ea104f088f05d5391d6226/cmd/inspektor-gadget/cmd/bcck8s.go#L110-L113

/cc @pothos because of commit 0549db2e37f3b348b84765aa65ef3a3f664cafac ("Filter first bcc tool lines and annotate nodes")

**Comment by pothos** [comment]
Maybe `if !post.firstLine {` needs an `else` where the `string(p)` is stored into the struct and used as prefix for the next invocation.
