### ISSUE TITLE
opensnoop (toolsMode=standard) fails running in a non-BTF kernel with vmlinux from BTFHub

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#339]
## Description

opensnoop (toolsMode=standard) fails running in a non-BTF kernel with vmlinux from BTFHub. 

Notice it works with `--tools-mode=auto` or `core`. Or if I delete the vmlinux file from the gadget container.

## Environment and steps to reproduce

**Set-up**: 
- Ubuntu-focal with Kernel 5.8 without `CONFIG_DEBUG_INFO_BTF`
- Kubeadm v1.22.2
- Docker v20.10.8

**Test**: 
```
$ kubectl logs -n kube-system $IG
...
Deployment options:
INSPEKTOR_GADGET_OPTION_TRACELOOP_LOGLEVEL=info,json
INSPEKTOR_GADGET_OPTION_TRACELOOP=true
INSPEKTOR_GADGET_OPTION_TOOLS_MODE=standard
INSPEKTOR_GADGET_OPTION_HOOK_MODE=fanotify
Inspektor Gadget version: v0.3.1-11-ga1b7164dc4be
BTF is not available: Trying BTFHub
Trying to download vmlinux from https://github.com/aquasecurity/btfhub/raw/main/ubuntu/20.04/x86_64/5.8.0-63-generic.btf.tar.xz
vmlinux downloaded at /boot/vmlinux-5.8.0-63-generic
...

$ ./kubectl-gadget opensnoop
bpf: Failed to load program: Invalid argument
FENTRY/FEXIT program can only be attached to another program annotated with BTF
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

Traceback (most recent call last):
  File "/bin/gadgets/opensnoop", line 340, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 488, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1456, in _trace_autoload
    self.attach_kretfunc(fn_name=func_name)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1136, in attach_kretfunc
    fn = self.load_func(fn_name, BPF.TRACING)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 528, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program kretfunc____x64_sys_open: Invalid argument

Error running command: command terminated with exit code 1
```

## Expected behavior

opensnoop (toolsMode=standard) must not depend on BTF.

## Additional information

Seems like opensnoop is internally relying on the existence of the vmlinux file to decide whether it can use the libbpf or not. The problem is that such a check is not enough because, like in my case, the user could have the vmlinux file but a kernel that does not support FENTRY/FEXIT.

**Comment by mauriciovasquezbernal** [comment]
Opensnoop tries to fentry/fexit programs if they are supported:

https://github.com/iovisor/bcc/blob/aa7200b9b2a7a2ce2e8a6f0dc1f456f3f93af1da/tools/opensnoop.py#L269

However, this check seems to be wrong as it only relies on the existence of the vmlinux file (other checks are not important) to determine if those programs are supported. 

https://github.com/iovisor/bcc/blob/aa7200b9b2a7a2ce2e8a6f0dc1f456f3f93af1da/src/python/bcc/__init__.py#L1085

I am not sure how that test should be changed. One idea is to be sure that the vmlinux file is loaded from the canonical path (sysfs), however I still need to understand all the considerations.

**Comment by mauriciovasquezbernal** [comment]
Opened upstream PR that fixes this: https://github.com/iovisor/bcc/pull/3810
