### ISSUE TITLE
[RFE] Move the flag --tools-mode from "kubectl-gadget deploy" to "kubectl-gadget <gadget-name>"

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#349]
## Current situation

We are currently installing both BCC and CO-RE versions of the gadgets into the container image. However, the user has to decide which version to use during the deployment phase and it can only be changed by uninstalling and re-installing the Inspektor Gadget. 

For instance, let's consider a user that decided to use CO-RE and some gadgets do not work because they need a newer kernel version. In such a situation, it will not be possible to run the BCC version of those gadgets that are not working even if they are already present in the image and would probably work.

## Impact

Users need to uninstall/reinstall Inspektor Gadget to try BCC-based or CO-RE gadgets.

## Ideal future situation

As proposed by Alban [here](https://github.com/kinvolk/inspektor-gadget/pull/334#issuecomment-938530000):

Remove the flag `--tools-mode` from `kubectl-gadget deploy` and add it in `kubectl-gadget opensnoop|execsnoop|...`.

**Comment by mauriciovasquezbernal** [comment]
As stated on https://github.com/kinvolk/inspektor-gadget/pull/473, we're not sure this a good change, hence I'll close this issue for now. Please feel free to reopen if anybody thinks it's still important.
