### ISSUE TITLE
[EPIC] Ensure we have good CI coverage across gadgets and platforms

### ISSUE THREAD

**Issue by margamanterola** [kinvolk/inspektor-gadget#370]
Currently, we have some integration tests that run as [GitHub actions](https://github.com/kinvolk/inspektor-gadget/blob/main/.github/workflows/inspektor-gadget.yml), but the actions are very limited: it compiles the container and then runs the [unit tests](https://github.com/kinvolk/inspektor-gadget/search?p=1&q=filename%3A%2A_test.go) and [integration tests](https://github.com/kinvolk/inspektor-gadget/tree/main/integration). Currently, the only integration test that we have is for Traceloop. We would like to have enough coverage that we can release changes with confidence that we’re not breaking existing functionality. 

This epic includes: 

- [x] #430
- Run the integration tests for different distributions and for different kernels. 
  - [ ] Run CI for AKS
  - [x] #561 
- [ ] Avoid running code integration tests for documentation changes. It could be met using `prow`, see https://github.com/kinvolk/inspektor-gadget/issues/689.
- [ ] #359 

[All issues with the area/ci label](https://github.com/kinvolk/inspektor-gadget/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fci)

**Comment by mauriciovasquezbernal** [comment]
Related https://github.com/kinvolk/inspektor-gadget/pull/561

**Comment by marga-kinvolk** [comment]
Work that was done but not linked here:
- https://github.com/kinvolk/inspektor-gadget/pull/469 - Jobs run in parallel in the CI, making it take less time.

**Comment by blanquicet** [comment]
Related https://github.com/kinvolk/inspektor-gadget/pull/670

**Comment by blanquicet** [comment]
I think our improvements so far are more than enough to close this EPIC. For the record, the following are the main improvements covered here:

- We run now Go linter in the CI: https://github.com/kinvolk/inspektor-gadget/issues/455.
- We added basic integration tests for all the gadgets in https://github.com/kinvolk/inspektor-gadget/pull/437, which has been parallelized and improved in different additional PRs.
- We started running the integration tests in an Azure RedHat Openshift (ARO) cluster: https://github.com/kinvolk/inspektor-gadget/pull/561.
- We are now installing the Security Profiles Operator on the testing cluster to test the gadgets that have the integration with the SPO: https://github.com/kinvolk/inspektor-gadget/pull/383.

For the remaining time of this quarter, we can try to merge https://github.com/kinvolk/inspektor-gadget/pull/702.

This week we can discuss the list of tasks to include in the CI EPIC for the next quarter.
