### ISSUE TITLE
Network Policy Advisor gadget: follow-up issues

### ISSUE THREAD

**Issue by alban** [kinvolk/inspektor-gadget#39]
The first iteration of Network Policy Advisor gadget was merged in https://github.com/kinvolk/inspektor-gadget/pull/37.

Follow-up issues:

- [X] User documentation (main readme, demo)
- [x] Unit tests for network policy report (#42)
- [ ] Developer documentation: A comment explaining how the network policies are generated from the packets would help a lot to understand it.
- [x] Print "ready" when it starts recording connections
- [x] Print "closing" after Ctrl+C
- [ ] Reconsider whether to use bcc-wrapper for the network-policy gadget
- [x] Make traceCollector thread safe.
- [ ] Sometimes, this error happens: `E0229 18:05:16.084586  704486 v2.go:147] short write`
- [x] Avoid "get pod,svc" calls with go-client for every new TCP connection (optimization) (#74)
- [x] Fix connections between pods across namespaces (https://github.com/kinvolk/inspektor-gadget/pull/42)
- [ ] Naming the network policy when the pod was created by a Job and not a Deployment

**Comment by marga-kinvolk** [comment]
There's a few items unchecked, but I'm not sure they are all that relevant right now. I'm going to close this issue and just note the open items in the current network-policy advisor epic. It will be up to whoever tackles that one to verify if they are still an issue.
