### ISSUE TITLE
[RFE] Check whether Inspektor Gadget works on Mariner

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/inspektor-gadget#405]
## Current situation

We don't know whether IG works on [Mariner](https://github.com/microsoft/CBL-Mariner) or not.

## Impact

People using Mariner don't know if they can use IG on top of it.

## Ideal future situation

We should verify if it works or not. If it doesn't work, then we should see what we need to do to make it work. If it works, then we can add it to the list of distributions that have been tested.

**Comment by mauriciovasquezbernal** [comment]
Duplicated of https://github.com/kinvolk/inspektor-gadget/issues/401, right?

**Comment by marga-kinvolk** [comment]
Yes... Sorry about the noise. We discussed this with Andy last week, I didn't check whether he had already filed the issue :-/
