### ISSUE TITLE
[RFE] seccomp-advisor: print created profile name

### ISSUE THREAD

**Issue by eiffel-fl** [kinvolk/inspektor-gadget#442]
## Current situation

Actually, when you create a seccomp profile using `seccomp-advisor`, gadget just inform you it created a profile:

```bash
$ ./kubectl-gadget seccomp-advisor start -m seccomp-profile -n seccomp-demo -p hello-python
kWjvNEsM1MmAWskS

$ ./kubectl-gadget seccomp-advisor stop kWjvNEsM1MmAWskS
Successfully created seccomp profile
```

## Impact

User has to use another command to get the profile name, which is not perfect in term of UX:

```bash
$ kubectl get seccompprofiles -A
NAMESPACE                    NAME           STATUS      AGE
gadget                       hello-python   Installed   4s
```

## Ideal future situation

Profile name should be printed when created:

```bash
$ ./kubectl-gadget seccomp-advisor start -m seccomp-profile -n seccomp-demo -p hello-python
kWjvNEsM1MmAWskS

$ ./kubectl-gadget seccomp-advisor stop kWjvNEsM1MmAWskS
Successfully created seccomp profile: gadget/hello-python
```

**Comment by blanquicet** [comment]
As discussed [here](https://github.com/kinvolk/inspektor-gadget/pull/421#issuecomment-989006475), please take into account that it might potentially be a list of profiles when we will start supporting more flexible filtering. Thanks!
