### ISSUE TITLE
[EPIC] Categorization and consistency thoughout the available gadgets 

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/inspektor-gadget#480]
## Background 
Inspektor Gadget includes many different gadgets that do different things. Currently, it’s hard to navigate the list of gadgets and each gadget functions differently, making it hard to easily use all of them. 
## Goal 
We will organize gadgets into separate categories and drive consistency across them. 
Gadgets in the same category should have consistent parameters and consistent output. 

## Categories
These are the suggested categories and what the new command line would look like. Names are still WIP.

* **Event streamers** (subcommand `events`). These gadgets intercept events happening on the nodes/namespaces/pods and generate streaming output as the events occur. They also allow to filter by namespace, label, pod, etc. 
* **Profilers** (subcommand `profile`). These gadgets run for a window of time gathering information of the state of the nodes/pods and then generate the output at the end. 
* **Top reporters** (subcommand `top`). These gadgets show the current activity sorted by the highest to the lowest in the key resource being observed, generating repeatedly updated output. 
* **Collectors** (subcommand `collect`). These gadgets generate snapshots of the state of the system at a given time 
* **Advisors** (subcommand `advisor`). These gadgets operate in two steps: first they gather information, then they generate a recommendation based on the information gathered. 

`Traceloop` doesn't really belong in any of these categories. It could be in a *Misc* category, that would eventually be joined by other external tools like pwru, tracepkt, etc.

We are planning on adding auditing mode for seccomp, and we already thought of a few ideas of other auditing gadgets. This would be another category *Auditors*.

## Subcommands and new gadget names
Having the categories be the new subcommands simplifies understanding what each gadget does. Some examples:
* `kubectl gadget events bind`
* `kubectl gadget events tcpconnect`
* `kubectl gadget profile cpu`
* `kubectl gadget profile biolatency`
* `kubectl gadget top bio`
* `kubectl gadget top files`
* `kubectl gadget top tcp`
* `kubectl gadget collect sockets`
* `kubectl gadget collect processes`
* `kubectl gadget advisor network-policy`

This has the advantage that the command line is a lot simpler and more consistent, it does have the disadvantage that the known BCC names (like execsnoop, for example) are no longer visible (although we can still support them, at least for a transitional period).

## Consistency markers
For each category, we want to ensure that the gadgets have consistent parameters and output. For example, the commands to start and stop the advisors should be the same, regardless of the advisor.

The CRD should be basically the same for all gadgets in that category.

The documentation can then document the commonalities first followed by the specific differences for each gadget.

The parameters to select and filter pods should be the same through all gadgets, as long as that functionality is available (some gadgets operate on the whole node rather than some pods).

## Work done
- [x] Finalize category names, subcommands and new subcommands for the corresponding gadgets.
- [x] #495 
- [x] #500 
- [x] #545
- [x] #546
- [x] #639 
- [x] #651 
- [x] #661 
- [x] #683 

## Pending work (for a future epic)
  - Check that all existing gadgets receive consistent parameters and produce consistent output.
  - Create documentation (and videos) for each category that explains the commonalities and the differences.
  - #366 
  - #598

**Comment by mauriciovasquezbernal** [comment]
> Event streamers (subcommand events). These gadgets intercept events happening on the nodes/namespaces/pods and generate streaming output as the events occur. They also allow to filter by namespace, label, pod, etc.

What about using naming these "tracers"?. Seems like trace is a well-known name to this one. 

> * `kubectl gadget events bind`
> 
> * `kubectl gadget events tcpconnect`
> 
> * `kubectl gadget profile cpu`
> 
> * `kubectl gadget profile biolatency`
> 
> * `kubectl gadget top bio`
> 
> * `kubectl gadget top files`
> 
> * `kubectl gadget top tcp`
> 
> * `kubectl gadget collect sockets`
> 
> * `kubectl gadget collect processes`
> 
> * `kubectl gadget advisor network-policy`

I was thinking if we should use something like `kubectl gadget <verb/action> <subject>`

- kubectl gadget trace bind 
- kubectl gadget trace tcpconnect 
- kubectl gadget advise network-policy

I'm not sure what we could use for `top`. 

> The CRD should be basically the same for all gadgets in that category.

Does it mean we'll have different CRDs for different categories?

**Comment by marga-kinvolk** [comment]
Yes, tracers / trace is another possibility. I was hesitant to use that one because our CRD is called "Trace", which kinda implies everything is a trace. I don't know if we would want to rename the CRD in that case.

> > The CRD should be basically the same for all gadgets in that category.

> Does it mean we'll have different CRDs for different categories?

Sorry, that was me being imprecise. What I meant to say is that the supported fields and values for the CRD should be the same. For example, the accepted values of the Output field might be different for different categories. Or the parameters that can be used to filter, or the accepted operations. I don't expect the CRD itself to change.

**Comment by marga-kinvolk** [comment]
The #500 PR that groups subcommands by category has been merged. With that, the next step is to look at each subcategory and ensure that the interface is consistent within.

**Comment by marga-kinvolk** [comment]
Closing this to mark this work as done. The pending items will be tracked in #721
