### ISSUE TITLE
Factorize documentation about `custom-columns` output

### ISSUE THREAD

**Issue by eiffel-fl** [kinvolk/inspektor-gadget#496]
Hi.

As [Mauricio stated](https://github.com/kinvolk/inspektor-gadget/pull/484#discussion_r800634650_):
>  I think it'll be nice to have a common document that describes it for all the gadgets instead of repeating it each time.

More generally, it would be cool to factorize our documentation.

Best regards.

**Comment by mauriciovasquezbernal** [comment]
I think it's a duplicated of https://github.com/kinvolk/inspektor-gadget/issues/495. Can we close it?

**Comment by eiffel-fl** [comment]
Oops! Sorry, I did not see you already opened it!
