### ISSUE TITLE
[RFE] Convert `mount...Euh! bindsnoop` to golang

### ISSUE THREAD

**Issue by eiffel-fl** [kinvolk/inspektor-gadget#509]

**Comment by mauriciovasquezbernal** [comment]
I hope we didn't step on each other feet this time -> https://github.com/kinvolk/inspektor-gadget/pull/510

**Comment by eiffel-fl** [comment]
Oops! I will get another one and edit the issue :D

**Comment by mauriciovasquezbernal** [comment]
It's now a duplicated of https://github.com/kinvolk/inspektor-gadget/issues/511, can we close it?
