### ISSUE TITLE
Implement CRD support for capabilities gadget

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#514]
There is not a libbpf-based version of the capabilities gadget on BCC yet. Anyway, we can add CRD support for this gadget by following this approach https://github.com/kinvolk/inspektor-gadget/pull/438/commits/73f4e5a44c8c549bbcb9d67a485ccd361ed6ddea.

**Comment by eiffel-fl** [comment]
Hi.

Maybe we should first try to convert the existing BCC gadget to CO-RE?
I will give a try to convert `capable.py` to CO-RE.

Best regards.

**Comment by mauriciovasquezbernal** [comment]
I think those are independent tasks. We could first implement the CRD support for the standard tracer and later on convert it to support CO-RE. Otherwise it's going to take a bit longer.
