### ISSUE TITLE
`waitForTraceState()` returns before dealing with all trace with the given ID

### ISSUE THREAD

**Issue by eiffel-fl** [kinvolk/inspektor-gadget#525]
https://kubernetes.slack.com/archives/CSYL75LF6/p1645443664396869 -> 

--- Slack message: 

Hi!  the watch api (https://github.com/kinvolk/inspektor-gadget/pull/398) does not seem to work on a 3 nodes clusters. I needed to add the following as a workaround:
https://gist.github.com/alban/2d5861aa0aad42b39bd204e066a5c681
Otherwise, it stops at the first "Added" event for the first node, and stops processing the following events.

**Comment by alban** [comment]
Symptoms: the dns or snisnoop gadgets only show output for one node.
