### ISSUE TITLE
cmd/kubectl-gadget: Print gathered output even if some traces timed out

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#560]
I wonder why we have a timeout in the first place, instead of waiting forever until it's ready?

_Originally posted by @alban in https://github.com/kinvolk/inspektor-gadget/pull/558#pullrequestreview-906179705_

**Comment by mauriciovasquezbernal** [comment]
> I wonder why we have a timeout in the first place, instead of waiting forever until it's ready

I think there are two reasons:
1. We don't want to block forever if there a problem in all the nodes
2. If a single node is having a problem, we can still collect information form other nodes

**Comment by blanquicet** [comment]
>     1. We don't want to block forever if there a problem in all the nodes
I agree we should keep a _very long_ timeout for the case where **all** of the traces neither meet the condition (remove the operation in the annotation or move into the expected state) nor set the `OperationError`. 

BTW, I said "_very long_" because yesterday I got again a timeout error even now that we set 5 sec thus it is not enough yet.

>     2. If a single node is having a problem, we can still collect information form other nodes
The fact is that we are not doing this. If at least one of the traces neither moves to the expected state nor sets the `OperationError`, the whole operation returns a timeout error and we do not show the output generated by the rest of the traces. 

This is the case I think we could still improve. For instance, we could start displaying the output generated by each trace once it meets the condition and find how to display that one of the nodes is not providing information (difficult for toppers). 

What do you think?

**Comment by marga-kinvolk** [comment]
As I've mentioned in other opportunities, having issues titled "Improve X" is not great, as there's always more that could be improved. If I'm reading the issue correctly, the proposal here is to show the output of gathered traces, even if other traces timed out. This sounds sensible to me.

**Comment by mauriciovasquezbernal** [comment]
Replaced by https://github.com/kinvolk/inspektor-gadget/issues/632.
