### ISSUE TITLE
dns/snisnoop: They are not working on OpenShift (ARO)

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#569]
## Description

DNS and Snisnoop gadgets fail to run in [Azure Red Hat OpenShift (ARO) cluster](https://docs.microsoft.com/en-us/azure/openshift/intro-openshift). They both fail with the same error:

```bash
POD                            TYPE      QTYPE      NAME
Error on node arocluster-5s247-worker-westeurope3-txds8, pod test-dns-4164121548280325190/test-pod: failed to attach tracer: failed to open raw socket: operation not permitted
```

## Environment and steps to reproduce

Once https://github.com/kinvolk/inspektor-gadget/pull/561 is merged, it will be enough to go to the [integration/integration_test.go](https://github.com/kinvolk/inspektor-gadget/blob/main/integration/integration_test.go) and avoid `TestDns` and `TestSnisnoop` tests are skipped for ARO (Azure RedHat OpenShift) distribution.

**Comment by alban** [comment]
Do we just miss the `NET_RAW` capability in `cmd/kubectl-gadget/deploy.go`?

**Comment by alban** [comment]
> You're absolutely right. Do you know why it wasn't required in other environments?

I don't know. I tried to find out but I didn't find an explanation.
