### ISSUE TITLE
Create a contribution guide

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#60]
The contribution guide is missing. It should contain something like:
- How to setup a development environment (consider using minikube or lokomotive cluster)
- How to compile (includes the local client and also how to build and push the container image)
- How to run the tests
- How to add a new gadget?

**Comment by vbatts** [comment]
:+1: would be good to lean on a consistent base for contribution guidelines. /cc @joaquimrocha

**Comment by mauriciovasquezbernal** [comment]
Solved by https://github.com/kinvolk/inspektor-gadget/pull/111
