### ISSUE TITLE
The gadget pod fails to start when using minikube with kvm2 driver and hook mode auto (fanotify fails)

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/inspektor-gadget#612]
## Description

I tried to test IG in minikube as described in our [contributing docs](https://github.com/kinvolk/inspektor-gadget/blob/9088cadf658101468716c385f11a8cd85e8cec2a/docs/install.md#minikube), using the kvm2 driver and the cloud-native-bpf-workshop image. This used to work in the past but doesn't seem to work now. When deploying the gadget pod, it fails to start with this error:

```
Starting the Gadget Tracer Manager...
time="2022-04-13T12:43:08Z" level=info msg="GadgetTracerManager: hook mode: fanotify (auto)"
time="2022-04-13T12:43:08Z" level=info msg="GadgetTracerManager: enabling fallback podinformer"
time="2022-04-13T12:43:08Z" level=fatal msg="failed to create server cannot start runc fanotify: fanotify: init error, function not implemented"
```

If I set the hook mode to podinformer, it works fine. According to Jose's investigation, the problem seems to be that the kernel in the minikube image we are using doesn't enable `CONFIG_FANOTIFY`.

So, to fix this issue we should:

- [ ] Add documentation that mentions that the kernel needs to have `CONFIG_FANOTIFY` enabled to use the fanotify hook mode
- [ ] Verify that this is enabled before trying to use the fanotify hook, or alternatively catch the error and not fail to start the pod if the fanotify hook fails.

## Impact

We have a documented way of testing Inspektor Gadget that doesn't work.

## Environment and steps to reproduce

1. **Set-up**: Run minikube using `kvm2` driver as described [here](https://github.com/kinvolk/inspektor-gadget/blob/9088cadf658101468716c385f11a8cd85e8cec2a/docs/install.md#minikube)
2. **Task**: Deploy Inspektor Gadget in the cluster, with default options
3. **Action(s)**:
  a. `kubectl-gadget deploy | kubectl apply -f -`
  b. `kubectl get pods -n gadget`
  c. `kubectl logs -n gadget gadget-<suffix>` 
4. **Error**:
```
OS detected: Buildroot 2020.02.2
Kernel detected: 5.4.40
bcc detected: 0.24.0-1
Gadget image: docker.io/kinvolk/gadget:francis-cli-consistency
Deployment options:
INSPEKTOR_GADGET_OPTION_FALLBACK_POD_INFORMER=true
INSPEKTOR_GADGET_OPTION_HOOK_MODE=fanotify
Inspektor Gadget version: v0.4.2-356-g963ddaf-dirty
Gadget Tracer Manager hook mode: fanotify
Kernel provided BTF is not available: Trying shipped BTF files
shipped BTF not available. Trying to download from BTFHub
Trying to download vmlinux from https://github.com/aquasecurity/btfhub-archive/raw/main/buildroot/2020.02.2/x86_64/5.4.40.btf.tar.xz
BTF not found
Starting the Gadget Tracer Manager...
time="2022-04-13T14:31:33Z" level=info msg="GadgetTracerManager: hook mode: fanotify"
time="2022-04-13T14:31:33Z" level=info msg="GadgetTracerManager: enabling fallback podinformer"
time="2022-04-13T14:31:33Z" level=fatal msg="failed to create server cannot start runc fanotify: fanotify: init error, function not implemented"
```

## Expected behavior

The pod should start with a valid hook mode

## Additional information

We use minikube with the docker driver in our CI, we don't currently have an integration test that validates de kvm2 mode, so it's unclear for how long this has been broken.

**Comment by alban** [comment]
From your logs:

```
GadgetTracerManager: hook mode: fanotify (auto)
```

It means that `runcfanotify.Supported()` (called from [here](https://github.com/kinvolk/inspektor-gadget/blob/a963be9a1dbed14c0670200c5cfd9980d06c6173/pkg/gadgettracermanager/gadgettracermanager.go#L242-L243)) returns true, even though it's not actually supported.

At the moment, `runcfanotify.Supported()` only checks is we can find the runc binary but does not check if fanotify_* system calls are working. It should have a test for the `fanotify_init` system call and return false when not supported, so the fallback mechanism can work as intended.

**Comment by blanquicet** [comment]
> I guess we shouldn't add the fallback if the auto selection selected podinformer?
>

Agree. Currently, we do not add the podinformer fallback only if the user explicitly asked for podinformer but not if the auto selection selected the podinformer:

https://github.com/kinvolk/inspektor-gadget/blob/a963be9a1dbed14c0670200c5cfd9980d06c6173/pkg/gadgettracermanager/gadgettracermanager.go#L261-L264
