### ISSUE TITLE
[RFE] Do not pin the filtering eBPF map

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#619]
## Current situation

Most gadgets can generate events for a specific container or for all the containers within a given pod, namespace or labels. To do so, the gadgets use an eBPF map with the mount namespace of the containers they are interested in. In particular, this map is created by the userspace code with the list of mount namespace (i.e. containers) requested by the user and it is used by the kernel space code to propagate only the events from the requested containers.
 
Currently, the userspace code has to pin this eBPF map and pass its path as a string to the kernel space code instead of passing the map itself, as it should be. Example:

https://github.com/kinvolk/inspektor-gadget/blob/e2a88779e8ce5212f6c2230a8e3cfbcd2f6b5ea1/pkg/gadgets/bindsnoop/tracer/interface.go#L22-L25

As mentioned in the comment, it had to be done in this way because of two issues found in the cilium/ebpf library:

- [ ] https://github.com/cilium/ebpf/issues/515
- [ ] https://github.com/cilium/ebpf/issues/517

## Impact

To be able to pin eBPF maps, it is necessary to do it in a directory of type `bpf`. Inspektor Gadget uses the directory `/sys/fs/bpf` because, [from v238](https://github.com/systemd/systemd/commit/43b7f24b5e0dd048452112bfb344739764c58694), systemd automatically mounts it as `bpf`. However, we need to apply a workaround for systems where such directory is not `bpf` due to they use an older version of systemd (for instance, AKS currently uses v237) or special systems like minikube (see [here](https://github.com/kinvolk/inspektor-gadget/blob/b50d93f8812a0ce049c1289b50aa060f228efd7b/gadget-container/entrypoint.sh#L45-L47)).

## Ideal future situation

eBPF maps are passed as maps and they are not pinned.

## Implementation options

Notice that issue 515 was already solved upstream and maybe by following the suggestion maintainers did on it we could avoid issue 517. 

## Important information

Solving this issue is very important for `local-gadget` because it runs in the node itself and the workaround we use for Inspektor Gadget (i.e. within the `gadget` pod, see [here](https://github.com/kinvolk/inspektor-gadget/blob/b50d93f8812a0ce049c1289b50aa060f228efd7b/gadget-container/entrypoint.sh#L45-L54)), are too invasive and should be avoided directly in the node.

**Comment by mauriciovasquezbernal** [comment]
I checked if we could avoid pinning the maps with the lasted cilium/ebpf library. Even if https://github.com/cilium/ebpf/issues/515 is solved, https://github.com/cilium/ebpf/issues/517 is still not fixed and doesn't allow us to avoid pinning the map. I'm [discussing](https://github.com/cilium/ebpf/issues/517#issuecomment-1106834297) with the cilium/ebpf community so see if we can find a solution for it.
