### ISSUE TITLE
[RFE] Do not create the `containers` eBPF map for local-gadget

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#620]
## Current situation

The `containers` eBPF map is created at `/sys/fs/bpf/gadget/containers` by the package `containersmap` to expose the container details for each mount namespace.

This map is used by the Python-based gadgets to enrich the output with the Kubernetes metadata of the containers.

## Impact

As described in https://github.com/kinvolk/inspektor-gadget/issues/619, it is a problem for systems where `/sys/fs/bpf` is not `bpf`.

## Ideal future situation

Given that the `local-gadget` does not use the Python-based gadgets thus it does not use the `containers` map, we should not create it for `local-gadget`. It will remove also the need of having a directory of type `bpf` and all the issues it involves.

**Comment by alban** [comment]
Note that the audit-seccomp gadget uses the containers map too.

**Comment by mauriciovasquezbernal** [comment]
> Note that the audit-seccomp gadget uses the containers map too.

Right. I think the point here is not to pin the map, but it can still be created and passed as an *ebpf.Map to the gadgets that need it.

**Comment by alban** [comment]
Fixed by https://github.com/kinvolk/inspektor-gadget/pull/654
