### ISSUE TITLE
gadget pod status get Error when deploying 

### ISSUE THREAD

**Issue by teyenliu** [kinvolk/inspektor-gadget#63]
I followed instructions to install in Kubernetes 
   and saw that gadget pod status was error.
If I check logs, I get the following error message:

$ kubectl logs gadget-pk25d -n kube-system
OS detected: "Ubuntu 18.04.4 LTS"
Kernel detected: 4.15.0-91-generic
bcc detected: 0.1.8-2570.git.ab54de2e
Gadget image: docker.io/kinvolk/gadget:latest
Inspektor Gadget version: v0.1.0-alpha.5-2-gde898ad
traceloop version 2b2bcfb
I0416 06:53:44.095459   26353 podinformer.go:257] Starting Pod controller
Sync/Add/Update for Pod kube-system kube-proxy-gjfg5:
    docker://1be89467637bfb2bbb2fec45e38b3f8ca40f781dd9ef8c99f81c55b40bf47876
pid 26353 tid 26408
overflow while guessing uts namespace, bailing out

Does anyone help on this?

**Comment by mauriciovasquezbernal** [comment]
Hi @teyenliu, 

Inspketor Gadget requires a newer kernel version to work, you can find the details [here](https://github.com/kinvolk/inspektor-gadget/blob/master/Documentation/install.md#using-lokomotive-on-flatcar-edge) & [here](https://github.com/kinvolk/inspektor-gadget/blob/master/Documentation/install.md#on-another-kubernetes-distribution).

We are already trying to make it more generic to work on older kernel version as well as in other Kubernetes distributions: https://github.com/kinvolk/inspektor-gadget/pull/58.

**Comment by alban** [comment]
> overflow while guessing uts namespace, bailing out

I could reproduce this problem on my Fedora laptop. I will prepare a fix.

**Comment by alban** [comment]
@teyenliu does it work with the build from https://github.com/kinvolk/inspektor-gadget/pull/64/checks?

(see "Artifacts" on the right)

**Comment by teyenliu** [comment]
> @teyenliu does it work with the build from https://github.com/kinvolk/inspektor-gadget/pull/64/checks?
> 
> (see "Artifacts" on the right)

@alban 
Thanks for your fix and info. I will try it on my testbed.

**Comment by teyenliu** [comment]
@alban 
It works on my testbed, but I encounter another BPF issue when I try the network policy demo as follows:
$ kubectl gadget network-policy monitor --namespaces demo --output ./networktrace.log
cannot write "r128:rtcp_v4_connect tcp_v4_connect\n" to kprobe_events: write /sys/kernel/debug/tracing/kprobe_events: device or resource busy
cannot write "r128:rtcp_v6_connect tcp_v6_connect\n" to kprobe_events: write /sys/kernel/debug/tracing/kprobe_events: device or resource busy
Error detected: "Error running command: \"command terminated with exit code 1\"\n"

It seems there are two BPF programs concurrently hook rtcp_v4_connect because I use Cilium as CNI.
Do you have any suggestions?

**Comment by alban** [comment]
As far as I know, Cilium uses network BPF programs but not kprobes. Could I see the list of kprobes on your system?
```
sudo cat /sys/kernel/debug/tracing/kprobe_events
sudo bpftool prog list
```

It might be a left-over kprobe from a previous execution of the network-policy gadget. Maybe the cleanup code is not working:
https://github.com/kinvolk/inspektor-gadget/blob/de898ad1d1f3cd4d404a5804da5a9167f033a0f8/gadget-container/gadgets/bcck8s/bcc-wrapper.sh#L108-L123

**Comment by teyenliu** [comment]
@alban 
Thanks for your hint. I find that the issue is caused by having Weave Scope at the same time. 
Before deleting Weave Scope:
$ sudo cat /sys/kernel/debug/tracing/kprobe_events
p:kprobes/ptcp_v6_connect tcp_v6_connect
p:kprobes/ptcp_set_state tcp_set_state
p:kprobes/pfd_install fd_install
r:kprobes/rfd_install fd_install
p:kprobes/ptcp_v4_connect tcp_v4_connect
r:kprobes/rtcp_v4_connect tcp_v4_connect
r:kprobes/rtcp_v6_connect tcp_v6_connect
p:kprobes/ptcp_close tcp_close
r:kprobes/rinet_csk_accept inet_csk_accept
p:kprobes/pfree_uts_ns free_uts_ns
p:kprobes/pcap_capable cap_capable

After deleting Weave Scope:
$ sudo cat /sys/kernel/debug/tracing/kprobe_events
p:kprobes/pfree_uts_ns free_uts_ns
p:kprobes/pcap_capable cap_capable

Then, the network-policy demo is working....
Thanks a lot.

**Comment by alban** [comment]
@teyenliu good that it works for you now. I filed https://github.com/weaveworks/tcptracer-bpf/issues/70 to keep track of this other issue.
