### ISSUE TITLE
ci/integration-tests: audit-seccomp is not working on ARO

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#631]
## Description

The integration test for the `audit seccomp` gadget is always failing on ARO. In particular, it fails while waiting for the test-pod to [get ready](https://github.com/kinvolk/inspektor-gadget/blob/79af7fc247ec15df63c1dec3d06036fbdf11522b/integration/integration_test.go#L187).

After a further investigation, I noticed that the `test-pod` does not become ready within 30 seconds because the seccomp profile it is using, takes a long time to get installed in all the nodes. I added an additional step on the integration test to wait for the seccomp profile and measure how much time it needs to be installed in all the nodes and I found that it is taking around 2min and 13sec.

```bash
$ kubectl apply -f - <<EOF
	 apiVersion: security-profiles-operator.x-k8s.io/v1beta1
	 kind: SeccompProfile
	 metadata:
	   name: log
	   namespace: test-audit-seccomp-7804149523170726494
	   annotations:
		 description: "Log some syscalls"
	 spec:
	   defaultAction: SCMP_ACT_ALLOW
	   architectures:
	   - SCMP_ARCH_X86_64
	   syscalls:
	   - action: SCMP_ACT_KILL
		 names:
		 - unshare
	   - action: SCMP_ACT_LOG
		 names:
		 - mkdir
	 EOF
seccompprofile.security-profiles-operator.x-k8s.io/log created

$ time kubectl wait sp --for condition=ready -n test-audit-seccomp-7804149523170726494 log --timeout=-1s
real	2m 13.43s
user	0m 0.08s
sys	0m 0.03s
```

Entire log [here](https://github.com/kinvolk/inspektor-gadget/runs/6176232131?check_suite_focus=true).

## Impact

It is not possible to run the integration test to verify the `audit seccomp` gadget is working properly on ARO.

## Environment and steps to reproduce

Once https://github.com/kinvolk/inspektor-gadget/pull/561 is merged, it will be enough to go to the [integration/integration_test.go](https://github.com/kinvolk/inspektor-gadget/blob/main/integration/integration_test.go) and avoid `TestAuditSeccomp` test is skipped for ARO distribution.

## Expected behavior

Is it normal it takes that long? Investigate what is happening.

**Comment by marga-kinvolk** [comment]
Can't we just wait for the profile to get installed as part of the test? I share the concern of why this is slow, but with how many nodes ARO deploys, maybe it's to be expected?

**Comment by blanquicet** [comment]
Yeah, we could wait for it and set a 3 min timeout but the overall CI workflow time will be also increased by these 3 minutes. So I was thinking of first evaluating what is going on before adding such a delay. What do you think?

**Comment by marga-kinvolk** [comment]
I didn't know it was working fine before. In that case, yeah, it seems likely that a recent change in the SPO caused this. Can we install the latest release instead of the main branch?

**Comment by blanquicet** [comment]
Yeah, that's what I am planning to do.
