### ISSUE TITLE
Gadgets don't work when the tracer controller is dead on a node 

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#632]
The current logic to run a gadget is:
1. Create a trace for each node on the cluster https://github.com/kinvolk/inspektor-gadget/blob/79af7fc247ec15df63c1dec3d06036fbdf11522b/cmd/kubectl-gadget/utils/trace.go#L194
2. Wait for **all** traces to move to the expected state https://github.com/kinvolk/inspektor-gadget/blob/79af7fc247ec15df63c1dec3d06036fbdf11522b/cmd/kubectl-gadget/utils/trace.go#L325
3. Print trace output https://github.com/kinvolk/inspektor-gadget/blob/79af7fc247ec15df63c1dec3d06036fbdf11522b/cmd/kubectl-gadget/utils/trace.go#L899 or start stream https://github.com/kinvolk/inspektor-gadget/blob/79af7fc247ec15df63c1dec3d06036fbdf11522b/cmd/kubectl-gadget/utils/trace.go#L874 depending on the kind of the gadget

The second step requires all trace controllers on the cluster to be working fine so they can update the state of the trace. If one (or more) of the controllers doesn't update the state, the whole operation fails.

## How to reproduce
1. Have a cluster with 2+ nodes
2. Shutdown a worker node (other techniques like killing the gadget tracer manager could work, but it's more complicated...)
```
NAME             STATUS     ROLES                  AGE    VERSION
ubuntu-hirsute   Ready      control-plane,master   153d   v1.22.2
worker           NotReady   <none>                 17m    v1.23.3
```
3.  Try to run any gadget 
```
$ ./kubectl-gadget trace exec
NODE             NAMESPACE        POD              CONTAINER        PCOMM            PID    PPID   RET ARGS
Error: failed to run gadget: timed out waiting for the condition
$ ./kubectl-gadget snapshot process
Error: timed out waiting for the condition
```

## Possible solution
I think that (for some cases) we can ignore the traces that don't move to the expected state and continue with the ones that moved. A warning to the user should be printed to be sure they're aware that the results from some nodes are not shown in the output.

**Comment by mauriciovasquezbernal** [comment]
Related to https://github.com/kinvolk/inspektor-gadget/issues/560.

**Comment by blanquicet** [comment]
> Related to #560.

I think this issue can completely replace #560 given that it is better explained and detailed.

**Comment by marga-kinvolk** [comment]
Yeah, I'm fine with this one replacing #560, but do note that we also saw this problem when there were no matches on a given node, because the trace was not marked as completed (i.e. the controller being dead is not the only reason why this would happen, anything that causes the trace not to be marked as completed causes this).

**Comment by mauriciovasquezbernal** [comment]
I'll reopen this as #769 doesn't handle the case when the controller is dead on a node.
