### ISSUE TITLE
gadgets: Uniform filtering map name

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#662]
All gadgets have an eBPF map used to filter the events. This map is sometimes called `mount_ns_set` and others `filter`. We should use the same name everywhere. 

Ref https://github.com/kinvolk/inspektor-gadget/pull/654#discussion_r871551754

**Comment by mqasimsarfraz** [comment]
@mauriciovasquezbernal How about using `mount_ns_set` everywhere? We can also maybe drop `_set` suffix. What do you think?

**Comment by mauriciovasquezbernal** [comment]
It'd be nice if we are able to include the filter word there to make it clear this map is used for filtering. What about `mount_ns_filter`? 

/cc @alban

**Comment by mqasimsarfraz** [comment]
Sounds good to me. I will use `mount_ns_filter`
