### ISSUE TITLE
[RFE] Use CO-RE for `tcptracer`

### ISSUE THREAD

**Issue by eiffel-fl** [kinvolk/inspektor-gadget#678]
Sadly, the eBPF code for `tcptracer` does not exist at the moment.

**Comment by mauriciovasquezbernal** [comment]
I think it was done in https://github.com/kinvolk/inspektor-gadget/pull/518, are you referring to a different gadget?

**Comment by eiffel-fl** [comment]
I am totally in the moon... Thank you:
`s/connect/tracer/`

**Comment by mauriciovasquezbernal** [comment]
Then it's a duplicated of https://github.com/kinvolk/inspektor-gadget/issues/609. Closing.
