### ISSUE TITLE
Add unified network command to monitor UDP packets, TCP connect and TCP accept

### ISSUE THREAD

**Issue by pothos** [kinvolk/inspektor-gadget#7]
For network policy hints it would be good to have all of this. But for the beginning maybe it's enough to state the limitations…

An implementation could attach to the syscalls that initiate/accept TCP connections and those that send/receive UDP packets. This does not catch TCP connections which have been established before the tracing starts.

Another idea would be to monitor all IP packets from a pod through a cgroup socket attachment. These filters are not attached to the whole system but just a specific cgroup. It just means having overhead at a different place (pod instead of system) because now every packet is analyzed. (Maybe this can be turned into an advantage by allowing to generate a pod package dump in the PCAP format.)

**Comment by mauriciovasquezbernal** [comment]
@alban  is this solved by https://github.com/kinvolk/inspektor-gadget/pull/37?

**Comment by alban** [comment]
> @alban is this solved by #37?

Yes, although it does not handle UDP packets. UDP is less common so I think it is not the priority. One idea to explore could be to use [DataDog's fork](https://github.com/DataDog/datadog-process-agent/tree/master/ebpf) of tcptracer-bpf with UDP support

**Comment by marga-kinvolk** [comment]
So, part of this issue was solved by introducing the network policy advisor, although it doesn't have UDP support. We have an issue about improving the network policy advisor and making it more useful, which includes adding UDP support to it (#373). I'm going to close this bug now.
