### ISSUE TITLE
[RFE] Add support for CO-RE gadgets on local-gadget

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#720]
## Current situation

Currently, only the following gadgets are supported on local-gadget:

```bash
$ sudo ./local-gadget
WARN[0000] Runtime enricher (containerd): failed to get current containers
WARN[0000] Runtime enricher (cri-o): failed to get current containers
» list-gadgets
audit-seccomp
dns
seccomp
snisnoop
socket-collector
```

## Impact

It is not possible to run gadgets like execsnoop, opensnoop and many others that already have their CO-RE implementation and would definitely work on local-gadget.

## Ideal future situation

- [ ] local-gadget should support all the CO-RE gadgets that make sense for its context.
- [ ] Add integration-tests using JSON format. The transformation from JSON to columns should be tested by the unit-tests described in https://github.com/kinvolk/inspektor-gadget/issues/719. 

## Pre-requirements

- [ ] The same PR that addresses this issue should be the same that addresses https://github.com/kinvolk/inspektor-gadget/issues/638 or should be created on top of it.

**Comment by blanquicet** [comment]
> I think it's highly related to #638, right?

Yeah but 638 is not a requirement for implementing this. We do not need to be able to do `local-gadget trace exec` to support `execsnoop` in local-gadget. In fact, we can start adding support for CO-RE gadgets using the current interactive approach as Alban described in [this comment](https://github.com/kinvolk/inspektor-gadget/issues/717#issuecomment-1169822058).

**Comment by mauriciovasquezbernal** [comment]
IMO we should go directly with #638 instead of adding some support that will be heavily modify in ~2 months.

**Comment by blanquicet** [comment]
Yeah, makes sense. 

To summarize, the same PR that addresses this issue should be the same that addresses #638 or should be created after 638 is closed. I added this to the issue description.

**Comment by blanquicet** [comment]
Issues https://github.com/kinvolk/inspektor-gadget/issues/720 and https://github.com/kinvolk/inspektor-gadget/issues/638 where redefined to define better what they cover. It implies that this issue is not needed anymore.
