### ISSUE TITLE
Inspektor Gadget doesn't work on an ARO cluster when livenessprobes are enabled

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#799]
We run the integration tests in a pre-created ARO cluster (https://github.com/kinvolk/inspektor-gadget/blob/main/docs/ci.md#run-integration-tests-on-an-aro-cluster). After recreating the cluster, I found out that the deploying of Inspektor Gadget when using liveness probes fails to this cluster.

One of the gadget pods never reaches the `READY` state, the liveness probe keeps failing and the pod is restarted, the the whole process repeats from the beginning. This node has a high number of pods:

```
$ kubectl get pods -o wide -A | grep "master-0" | wc -l
```

I deployed it without liveness probe to perform some debugging, I collected the following logs from the failing pod:

```
[...]
Starting the Gadget Tracer Manager...
time="2022-08-03T15:11:15Z" level=info msg="GadgetTracerManager: hook mode: none"
time="2022-08-03T15:11:15Z" level=info msg="GadgetTracerManager: enabling fallback podinformer"
time="2022-08-03T15:11:15Z" level=info msg="Starting Pod controller"

[...] 
// a lot of messages like the following are printed
level=warning msg="container XXX wasn't detected by the main hook! The fallback pod informer will add it."
[...]
time="2022-08-03T15:12:32Z" level=info msg="Serving on gRPC socket /run/gadgettracermanager.socket"
```

It takes around 77 seconds to start, by default the liveness probe has a initial delay of 60 seconds, a period of 5 seconds and 3 failures. (60 + 5*3= 75). It indicates the gadget pod is not starting fast enough to avoid the liveness probes killing it. 

The purpose of this issue is:
- [x] Investigate1 why Inspektor Gadget takes too long to start on such conditions (high number of pods)
- [ ] Determine if we should continue using liveness probes or we should tune up the default parameters

**Comment by blanquicet** [comment]
If we decide that it is needed to increase the initial delay of the liveness probe, then we should consider using the [`startupProbe`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes) instead of the `initialDelaySeconds`.

**Comment by mauriciovasquezbernal** [comment]
I checked the status of this on an ARO cluster:

```
$ ./kubectl-gadget deploy --image=ghcr.io/kinvolk/inspektor-gadget:v0.8.0
Creating Namespace/gadget...
Creating ServiceAccount/gadget...
Creating Role/gadget-role...
Creating RoleBinding/gadget-role-binding...
Creating ClusterRole/gadget-cluster-role...
Creating ClusterRoleBinding/gadget-cluster-role-binding...
Creating DaemonSet/gadget...
Creating CustomResourceDefinition/traces.gadget.kinvolk.io...
Waiting for gadget pod(s) to be ready...
0/6 gadget pod(s) ready
0/6 gadget pod(s) ready
1/6 gadget pod(s) ready
2/6 gadget pod(s) ready
3/6 gadget pod(s) ready
4/6 gadget pod(s) ready
5/6 gadget pod(s) ready
Error: timed out waiting for the condition

.... 
$ ./kubectl-gadget deploy --image=ghcr.io/kinvolk/inspektor-gadget:latest
Creating Namespace/gadget...
Creating ServiceAccount/gadget...
Creating Role/gadget-role...
Creating RoleBinding/gadget-role-binding...
Creating ClusterRole/gadget-cluster-role...
Creating ClusterRoleBinding/gadget-cluster-role-binding...
Creating DaemonSet/gadget...
Creating CustomResourceDefinition/traces.gadget.kinvolk.io...
Waiting for gadget pod(s) to be ready...
0/6 gadget pod(s) ready
1/6 gadget pod(s) ready
2/6 gadget pod(s) ready
3/6 gadget pod(s) ready
4/6 gadget pod(s) ready
5/6 gadget pod(s) ready
6/6 gadget pod(s) ready
Inspektor Gadget successfully deployed
```

I think this problem is fixed. I'll close this issue and open https://github.com/kinvolk/inspektor-gadget/pull/1005 to enable them again on aro.
