### ISSUE TITLE
top ebpf fails on AKS because of read-only /proc

### ISSUE THREAD

**Issue by alban** [kinvolk/inspektor-gadget#850]
## Description

`kubectl gadget top ebpf` fails on AKS (Linux 5.4.0-1089-azure):
```
failed to create tracer: could not enable stat collection: open /proc/sys/kernel/bpf_stats_enabled: read-only file system
```

* With the command `kubectl gadget top ebpf`, the error message is difficult to read because the screen gets refreshed every second.
* With `-o json`, the error message is easier to read

## Impact

Cannot use `top ebpf` on AKS

## Environment and steps to reproduce

1. **Set-up**: AKS (Linux Linux 5.4.0-1089-azure)
2. **Task**:
3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. `kubectl gadget top ebpf`
  b. `kubectl gadget top ebpf -o json`
4. **Error**:
```
Error: failed to run gadget on node "aks-agentpool-37135575-vmss000000": failed to create tracer: could not enable stat collection: open /proc/sys/kernel/bpf_stats_enabled: read-only file system
```

## Expected behavior

* Errors are displayed correctly without being erased even without using `-o json`
* Fall back to `bpf_stats_enabled` works fine.

## Additional information

`BPF_ENABLE_STATS` requires Linux 5.8 so it falls back on `/proc/sys/kernel/bpf_stats_enabled`. However, the gadget pod has `/proc` mounted read-only, so this fails.

Possible solution:
1. Mount /proc in read-write mode
2. Use `/host/proc/sys/kernel/bpf_stats_enabled`, which is mounted in read-write mode.

**Comment by alban** [comment]
Sysdig has an environment variable `$HOST_ROOT`. We could do the same:
* define `HOST_ROOT=/host` in deploy.yaml
* use filepath.Join(os.Getenv("HOST_ROOT"), "/proc/sys/kernel/bpf_stats_enabled")

**Comment by flyth** [comment]
Thanks for the detailed information on this!
The `HOST_ROOT` way seems to be used by different other projects, so I'll add that.

> Errors are displayed correctly without being erased even without using -o json

This probably has to be fixed in a more generic way since all gadgets with a `utils.ClearScreen()` will probably have that issue. (It's not sent back to the loop but printed here: https://github.com/kinvolk/inspektor-gadget/blob/main/cmd/kubectl-gadget/utils/trace.go#L593)
