### ISSUE TITLE
`kubectl gadget version` should also report version of Inspektor Gadget on the nodes

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#902]
`kubectl` reports both, the client and server versions:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

kubectl gadget only reports the client version:
```
 $ ./kubectl-gadget version
v0.7.1-58-g8d0b3c2e-dirty
```

It should report both of them to make it easier for users to check the version they have deployed on the cluster.

**Comment by mauriciovasquezbernal** [comment]
> Should we really do this?

It seems to me it's useful for debugging purposes. 

> More particularly, what are the guarantees we offer when someone uses different versions of the CLI and server?

None so far. I suppose this is something we'll be considering once we approach to v1.0.

**Comment by alban** [comment]
> If we permit users to use different versions for the CLI and the server, then this feature is definitely needed.
> Otherwise, I do not really see the point of printing two times the same version?

It might not be the same version if the user didn't deploy IG yet, or if they switch to a different $KUBECONFIG and they want to check if the version is correct, or if they want to check after an update of the CLI with `kubectl krew upgrade gadget`. For example:
```
$ kubectl gadget version
Client Version: v0.7.0
Server Version: not installed
$
```

=> The user needs to run `kubectl gadget deploy` to **install** it.

```
$ kubectl gadget version
Client Version: v0.7.1
Server Version: v0.6.0
$
```

=> The user needs to run `kubectl gadget deploy` to **update** it.

```
$ kubectl gadget version
Client Version: v0.7.0
Server Version: v0.7.0
$ kubectl krew upgrade gadget
$ kubectl gadget version
Client Version: v0.7.1
Server Version: v0.7.0
$ kubectl gadget deploy
$ kubectl gadget version
Client Version: v0.7.1
Server Version: v0.7.1
```

=> The user successfully update both the client and server

**Comment by mauriciovasquezbernal** [comment]
Related https://github.com/kinvolk/inspektor-gadget/pull/936.

**Comment by mauriciovasquezbernal** [comment]
> would it be possible to trigger an update of the node when running kubectl krew upgrade gadget?

I don't think so. krew only cares about updating the gadget binary and IMO it'll be very difficult to implement logic to run extra steps when updating a binary. I think the warning implemented in https://github.com/kinvolk/inspektor-gadget/pull/936 and some better documentation the release notes could help.

**Comment by burak-ok** [comment]
Should we check for a possible deviation on all pods?
For example if pod A runs version 0.1.0, pod B runs version 0.2.0 and the client is version 0.3.0

This kind of issue should not appear often, but i think that a check for this would help greatly when such a deviation happens.

**Comment by mauriciovasquezbernal** [comment]
I think it's useful to check that condition in case the installation is messed up (two different versions of Inspektor Gadget running on the same cluster).

**Comment by alban** [comment]
We can check the daemonset rather than individual pods.

**Comment by mauriciovasquezbernal** [comment]
Fixed by https://github.com/kinvolk/inspektor-gadget/pull/977.
