### ISSUE TITLE
[RFE] Decide what to do with the integration test image

### ISSUE THREAD

**Issue by eiffel-fl** [kinvolk/inspektor-gadget#944]
## Current situation

To run integration tests, we first build a docker image which contains a compiled binary containing our integration tests.
On release, this image is then pushed as [`inspektor-gadget-test`](https://github.com/kinvolk/inspektor-gadget/pkgs/container/inspektor-gadget-test).

## Impact

To keep our sanity, the integration tests jobs are factorized running in the [`run-integration-tests action`](https://github.com/kinvolk/inspektor-gadget/blob/3af35cb183c576b7a62f3887157e6b7701b5725a/.github/actions/run-integration-tests/action.yml).
As a consequence, this will mean the above image will built for each call to this action but also pushed on release.

## Ideal future situation

The goal here is to discuss what should we do about this particular image.
Should we stop publishing it somewhere? Should we only publish it once when all the integration tests suceeded?

**Comment by mauriciovasquezbernal** [comment]
I'd like to discuss better the goal of publishing that image. IIUC the initial idea was to provide an easy way for Kubernetes administrators to test if Inspektor Gadget works fine on a given cluster by using the `gadget-integration-test-job.yaml` release manifest. I'm not totally convinced that's useful, I think if somebody needs to test Inspektor Gadget they could run the integration tests manually by cloning the repo and running `make -C integration test` (or `make integration-test`).

I checked the [inspektor-gadget-test](https://github.com/kinvolk/inspektor-gadget/pkgs/container/inspektor-gadget-test) package and it has zero pulls for all images. 
![Selection_142](https://user-images.githubusercontent.com/13031921/190509572-0496673a-d5fb-46b4-8195-1df21fdf4f7f.png)

@alban I think you originally introduced this, do you have any opinion?

**Comment by blanquicet** [comment]
> > I checked the inspektor-gadget-test package and it has zero pulls for all images.
> 
> Based on this information, I would tend toward not pushing this image (and delete the corresponding repository) unless there is a really good use case for this image.

Agree

**Comment by mqasimsarfraz** [comment]
> > I checked the inspektor-gadget-test package and it has zero pulls for all images.
> 
> Based on this information, I would tend toward not pushing this image (and delete the corresponding repository) unless there is a really good use case for this image.

+1

**Comment by alban** [comment]
> OK, can you please explain what was the idea you had in mind with this image?

It was to run the IG tests on a specific Kubernetes environment without having to set up a CI. But it ended up not being used.

**Comment by mqasimsarfraz** [comment]
I opened the [PR](https://github.com/kinvolk/inspektor-gadget/pull/955) to remove it. Please feel free to add your reviews!
