### ISSUE TITLE
Reduce size of gadget container image

### ISSUE THREAD

**Issue by johananl** [kinvolk/inspektor-gadget#953]
The default gadget container image is currently 763 MB in size. Since this image must be downloaded by every k8s node against which gadgets are used, making the image smaller would improve deployment time. Furthermore, if the gadget pods are long running, there is value in reducing the attack surface of the image.

```
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
10f080f79008   9 minutes ago    RUN /bin/sh -c rm -f /var/run # buildkit        0B        buildkit.dockerfile.v0
<missing>      9 minutes ago    COPY /tmp/btfs /btfs/ # buildkit                0B        buildkit.dockerfile.v0
<missing>      9 minutes ago    COPY gadget-container/hooks/nri/conf.json /o…   202B      buildkit.dockerfile.v0
<missing>      9 minutes ago    COPY /gadget/gadget-container/bin/nrigadget …   12MB      buildkit.dockerfile.v0
<missing>      9 minutes ago    COPY gadget-container/hooks/crio/gadget-pres…   508B      buildkit.dockerfile.v0
<missing>      9 minutes ago    COPY /gadget/gadget-container/bin/ocihookgad…   14.9MB    buildkit.dockerfile.v0
<missing>      9 minutes ago    COPY gadget-container/hooks/oci/prestart.sh …   324B      buildkit.dockerfile.v0
<missing>      9 minutes ago    COPY /bin/traceloop /bin/ # buildkit            42.8MB    buildkit.dockerfile.v0
<missing>      9 minutes ago    COPY /gadget/gadget-container/bin/gadgettrac…   78.3MB    buildkit.dockerfile.v0
<missing>      13 minutes ago   COPY gadget-container/entrypoint.sh gadget-c…   9.65kB    buildkit.dockerfile.v0
<missing>      13 minutes ago   RUN /bin/sh -c set -ex;  export DEBIAN_FRONT…   70.9MB    buildkit.dockerfile.v0
<missing>      9 days ago       RUN /bin/sh -c apt-get update -y &&   DEBIAN…   454MB     buildkit.dockerfile.v0
<missing>      9 days ago       COPY /root/bcc/*.deb /root/bcc/ # buildkit      17MB      buildkit.dockerfile.v0
<missing>      2 weeks ago      /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>      2 weeks ago      /bin/sh -c #(nop) ADD file:ff6963f777661fb16…   72.8MB
```

Looking at the layers of the image, the main contributor to its size is the fact that we use **Debian** as a base image. I'm wondering if a SCRATCH image is out of the question. In case an interactive shell is needed for troubleshooting, there are more compact distros which could be considered.

Looks like we're using `bcc` as the main image, which in turn uses Debian. Do we really need BCC in Inspektor Gadget? What benefit does the BCC project add? Couldn't we compile the BPF programs provided by BCC ourselves using `clang` and load them using `cilium/ebpf`? If we could, I think we could switch to a more compact image.

**Comment by alban** [comment]
We provide two versions of the container image:
https://github.com/kinvolk/inspektor-gadget/pkgs/container/inspektor-gadget

* latest: contains both gadgets based on bcc and gadgets implemented with `cilium/ebpf` (better compatibility with older kernels)
* latest-core: smaller image without bcc.

**Comment by johananl** [comment]
Right, now I understand why two images are necessary. I guess we can close this then.
