### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#99]
The `gadgettracermanager` implements a `--dump` option to see the current list of containers and tracers. However, a log mechanism that shows more detailed information about the performed operations is missing.

The log for `ocihookgadget` is written by piping its output on the hooks scripts (https://github.com/kinvolk/inspektor-gadget/blob/d2afe65666fa844a9d883a342646dbbbfb3df889/gadget-container/ocihookgadget/runc-hook-poststop.sh#L4), we could consider writing the log directly from ocihookgadget. It's also logging errors, it's impossible to understand if a successful execution was performed.

**Comment by marga-kinvolk** [comment]
Mauricio, I'm not sure I understand what you are asking for here. Is it still relevant? Could you retitle the issue with something actionable? Thanks!

**Comment by mauriciovasquezbernal** [comment]
It was related to ocihookgadget, which is not so relevant anymore. I'll close it.
